[package]
name = "bitac-nostr-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.27"
nostr-bot = "0.3.0"
regex = "1.7.2"
reqwest = "0.11.14"
serde_json = "1.0.94"
tokio = "1.26.0"
